---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
  annotations:
    flux.weave.works/automated: 'true'
spec:
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: barfoo
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
      volumes:
      - name: barfoo
        persistentVolumeClaim:
          claimName: mysql
